python task2a_create_jsons.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py
python run_task2a_openai.py

python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python run_task2a_ollama_models.py
python combine_task2a_results.py
prepare_upload.bat