python task2b_create_jsons.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py
python run_task2b_openai.py

python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python run_task2b_ollama_models.py
python combine_task2b_results.py
prepare_upload.bat